name: Matrix 

on:
  push:

jobs:
  matrix-job:

    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest

        python-version:
          - 3.11
          - 3.12
          - 3.13

        include:
          - runner: macos-latest
            python-version: 3.12

        exclude:
          - runner: windows-latest
            python-version: 3.13

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Print Python Version

        run: |
          echo "Runner: ${{ matrix.runner }}"
          echo "Python Version: ${{ matrix.python-version }}"
